- src/main/java/com/ullink/slack/simpleslackapi/SlackPersona.java
- src/main/java/com/ullink/slack/simpleslackapi/impl/SlackPersonaImpl.java
The current mismatch in declared type (`Integer`) and returned type (`int`) results in Jackson throwing errors:
```
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.ullink.slack.simpleslackapi.impl.SlackMessagePostedImpl["channel"]->com.ullink.slack.simpleslackapi.impl.SlackChannelImpl["members"]->java.util.ArrayList[2]->com.ullink.slack.simpleslackapi.impl.SlackUserImpl["timeZoneOffset"])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:187)
at …
```
> Use Integer rather than int for return type of getTimeZoneOffset()

- README.md
- build.gradle
- src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java
- src/main/java/com/ullink/slack/simpleslackapi/impl/AbstractSlackSessionImpl.java
- src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java
- src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
I wanted to be able to post to a channel _without_ links unfurling themselves, this code should resolve that, by adding an unfurl boolean to the command.
I also added a method that removes the SlackAttachment parameter, because a lot of the time, you don't want to send one. Default functionality is unaltered, I bumped the version number to 0.5.1, and added myself as a contributor (not sure if I was supposed to do this, since it's such a small change).
> Add the option to turn off link unfurling

- src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONReplyParser.java
- src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
This PR is in response to issue #42.
This should work, I tested it as much as I knew how to. Essentially it's because the multiparty direct message returns `group`, not `channel`. Also if an error is thrown, the response is completely different, but the handle still expects that class. I did my best to make the error known to those who are writing their projects, and returned null.
Some error handling is needed, badly.
> Fix multiparty direct messages

- src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java
- src/main/java/com/ullink/slack/simpleslackapi/events/EventType.java
- src/main/java/com/ullink/slack/simpleslackapi/events/SlackEventType.java
- src/main/java/com/ullink/slack/simpleslackapi/events/SlackUserChange.java
- src/main/java/com/ullink/slack/simpleslackapi/impl/AbstractSlackSessionImpl.java
- src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
- src/main/java/com/ullink/slack/simpleslackapi/impl/SlackUserChangeImpl.java
- src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- src/main/java/com/ullink/slack/simpleslackapi/listeners/SlackUserChangeListener.java
- src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
Hello,
I have added the ability to listen to the user_change event from Slack. This event typically triggers when someone changes it's own nickname, or any other personal info.
Upon triggering of this event, the internal users map is also updated.
Thanks !
> Added Listener for the user_change Slack event type

- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
This is a method that can be used to set the presence of a slack bot. The persona on which the change is made is not mutable.
> Added SlackSession#setPresence(SlackPresence)

- samples/actions/src/main/java/actions/SendingMessages.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackPreparedMessage.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/AbstractSlackSessionImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
Hey,
This PR adds support for multiple attachments in a single slack message. Since there were already so many different constructors for `sendMessage`, I didn't want to either introduce a breaking change, nor an added constructor for each scenario, I decided to create a `SlackPreapredMessage` class. Said class has a builder for ease-of-use. An example usage would be:
```
public void sendUsingPreparedMessage(SlackSession session)
{
//get a channel
SlackChannel channel = session.findChannelByName("achannel");
//build a message object
SlackPreparedMessage preparedMessage = new SlackPreparedMessage.Builder()
.withMessage("Hey, this is a message")
.withUnfurl(false)
.addAttachment(new SlackAttachment())
.addAttachment(new SlackAttachment())
.build();
session.sendMessage(channel, …
```
> Support for multiple attachments

- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackSessionFactory.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
With this the delay between heartbeat requests can be changed. Can either be set with SlackSessionFactory#createWebSocketSlackSession, or changed with SlackSession#setHeartbeat(long, TimeUnit)
> Added mutable heartbeat value to SlackWebSocketSessionImpl

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackSessionFactory.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
Closes #74, and this resolves that issue. This change adds the previous existing constructor and prevents the creation of a HttpHost object with null parameters.
> Prevent IllegalArgumentException with WebSocketSlackSession.

- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackFile.java
This fields are no longer relevant and always contain null. According to official slack documentation: "Please note that the url and url_download parameters have been deprecated. Please use url_private and url_private_download instead."
> Annotating methods which access to url and urlDownload fields of SlackFile as deprecated

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
throws exception on SLACK_DISCONNECTED event as it was UNKNOWN
> Missing "break" in event dispatcher switch case

- sources/build.gradle
- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackAction.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackAttachment.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONAttachmentFormatter.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
Once Slack has introduced [Interactive buttons](https://api.slack.com/docs/message-buttons), we have to support "actions" field inside an "attachment".
> Adding SlackAction in SlackAttachment

- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackIntegration.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackPersona.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/AbstractSlackSessionImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackBotImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackIntegrationImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONParsingUtils.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONSessionStatusParser.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackPersonaImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackUserImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONSessionStatusParser.java
- sources/src/test/resources/test_json.json
This pull request fixes issue with user list and adds integrations support functionality.
**Issue**
While parsing rtm.start response in SlackJSONSessionStatusParser both users and bots arrays are merged into users array which cause mix of incompatible types because bots array contains slack integrations (probably SlackJSONSessionStatusParser author was confused by array name).
Here you may see issue example:
``` java
session.getUsers().stream().forEach(slackUser -> {
System.out.println(slackUser.getUserName() + " " + session.getPresence(slackUser));
});
```
Following code will fail as _session.getUsers()_ will also return integrations which may not be associated with Slack users.
Here is example of SlackUser instance which was created from Slack Integration (bots array):
> …
> Added integrations support

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
motivation:
when user registered listener throws, the exception is swallowed by the default
impl of Endpoint#onError (no-op)
changes:
* override Endpoint#onError in SlackWebSocketSessionImpl#connectImpl, log error
> override Endpoint#onError and log error when called

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
motivation:
currently, if you add two listeners to a message type, and the first throws,
the second will not be called.
changes:
* wrap the body of the loop iterating the listeners with try-catch
* catch Throwable and log as error
> ensure all listeners are called, even if exception is thrown from one

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
motivation:
when an unknown event occurs, this is logged:
11:56:14.337 [Grizzly(2)] ERROR c.u.s.s.i.SlackWebSocketSessionImpl - Endpoint#onError called
java.lang.IllegalArgumentException: event not handled com.ullink.slack.simpleslackapi.events.SlackEvent$1@70a36547
at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$EventDispatcher.dispatch(SlackWebSocketSessionImpl.java:206) ~[simple-slack-api-f1aacf20c28cfc4b96aa29067f7f0faa5594c664.jar:na]
not useful without the event type
changes:
* log event type in exception message
> log type of UNKNOWN events when throwing on them

- samples/events/src/main/java/events/ListeningToMessageEvents.java
The example was comparing the ID of the user to the sender of the message, instead of the ID of the sender.
> Fix sample for filtering messages by a user

- sources/build.gradle
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/utils/ReaderUtils.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/utils/ReaderUtilsTest.java
Guava is only used for converting reader to String.
A new utility is added to cover this case and
guava dependency is removed.
https://github.com/Ullink/simple-slack-api/issues/126
> Guava is removed from dependencies

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
The [channel_created](https://api.slack.com/events/channel_created) event
doesn't contain a channel topic or purpose, unlike the other channel-related events
(channel_joined, group_joined). This was causing a NPE when trying to parse the
channel object out of the event body:
```
16:36:08.710 [Grizzly(1)] DEBUG c.u.s.s.i.SlackWebSocketSessionImpl - receiving from websocket {"type":"channel_created","channel":{"id":"CXXXXXXX","is_channel":true,"name":"XXXX","created":1477067768,"creator":"UXXXXXXX","is_shared":false,"is_org_shared":false},"event_ts":"1477067768.798038"}
16:36:08.712 [Grizzly(1)] ERROR c.u.s.s.i.SlackWebSocketSessionImpl - Endpoint#onError called
java.lang.NullPointerException: null
at com.ullink.slack.simpleslackapi.impl.SlackJSONMessageParser.parseChannelDescription(SlackJS …
```
> Fix channel parsing from channel_created event

- build.gradle
without this, running `./gradlew idea` generates an ipr file which causes intellij to be unable to parse the sources
> fixup build.gradle to generate a correct ipr file

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
https://api.slack.com/rtm
client generated messages should have an `id` field, so that slack can mark the response with the same id
> populate `id` field in websocket messages generated by client

- sources/src/main/java/com/ullink/slack/simpleslackapi/events/ReactionAdded.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/events/ReactionRemoved.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/ReactionAddedImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/ReactionRemovedImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
This commit is a simple extension to the JSON parsing already in place
for reaction added/removed events. The "item_user" field already exists
in Slack's API response, seen [here](https://api.slack.com/events/reaction_removed) and [here](https://api.slack.com/events/reaction_added).
> Add "item_user" field to reactions

- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSessionWrapper.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
This pull request adds two overloaded 'sendFile' methods to SlackSession: one that accepts **SlackUser** and another that accepts **username as String**.
> Add 'send file to user' feature.

- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackPreparedMessage.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/events/SlackMessagePosted.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackMessagePostedImpl.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
With this PR, bots will be able to start threads / reply to threads.
Messages from threads are message events but with a "thread_ts" property to attach the message to a parent. Each message from the thread has the same "thread_ts" value.
I added this property (and the "reply_broadcast" property used to also display the message in the parent channel) in the SlackPreparedMessage, so this should not break the current state of the API.
I chose not to handle the hidden "message_replied" event. I used SlackEvent.UNKNOWN_EVENT as a fallback so no error is raised, but it could be implemented in a later stage.
Also, there is a bug referencing this: #172.
Slack API reference doc : https://api.slack.com/docs/message-threading
> Added ability to start/reply to threads

- samples/connection/src/main/java/com/ullink/slack/simpleslackapi/samples/connection/SlackDirectConnectionWithBuilder.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
Useful for cases where proxy presence is not known
in advance (e.g command tools).
Prior to this, 'IllegalArgumentException: Host name may not be null'
was thrown by HttpHost(containsNoBlanks), preventing to use
the builder when no proxy hostname is set.
> Allow no proxy in SlackSessionFactoryBuilder

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackWebSocketSessionImpl.java
This closes #215. More info in issue.
> NullPointerException while message sending

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/AbstractSlackSessionImpl.java
Near all email addresses are case insensitive. It'd make more sense to accept results with different casings
> Email casing

- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackAction.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackFile.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/SlackPreparedMessage.java
Without no args constructors it's impossible to use auto mapping between DTO and model with tools such as mapstruct
> No args constructors for slack messaging model

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackSessionFactory.java
- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
- sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackWebSocketSessionImpl.java
Needed for when slack.com is blocked but specific workspaces are not. For example, https://[myworkspace].slack.com/api/ can be used instead of the default https://slack.com/api/  
I also cleaned up some String literals of the api path that didn't use the constants
> functionality to optionally override the default slack api url

- sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
We're frequently seeing a lot of WARN messages in the logs about unknown event types being ignored. It would be nice to have this type of message logged at the DEBUG level so it can easily be filtered out from the logs.
> Change log level of unknown event occurrence from WARN to DEBUG

- sources/build.gradle
Complete Error: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of jetbrains/buildServer/plugins/classLoaders/PluginStandaloneClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/apache/catalina/loader/ParallelWebappClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
Closes #230
> fix: LoggerFactory has different implementation in runtime.
