Itiviti/simple-slack-api

.gitignore, build.gradle, settings.gradle, src/main/java/com/ullink/slack/simpleslackapi/SlackBot.java, src/main/java/com/ullink/slack/simpleslackapi/SlackChannel.java, src/main/java/com/ullink/slack/simpleslackapi/SlackPersona.java, src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, src/main/java/com/ullink/slack/simpleslackapi/SlackUser.java, src/main/java/com/ullink/slack/simpleslackapi/impl/AbstractSlackSessionImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackBotImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackChannelImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONParsingUtils.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONSessionStatusParser.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackMessageImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackUserImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java, src/test/resources/test_json.json
* persons and bots are both "persona", i.e. share some common attributes
* base implementation of slack presences
* channels can be direct (persona to persona) or shared
* a slack session is accordingly attached to a persona (either bot or person)
* fallback dispatch: if it is a slackmessage, dispatch to this
cosmetic:
* consolidated import statement (more wildcards)
* some toString implementations
This is my first pull request ever. If I did something wrong, I am very open for directions and corrections. I like your library very much, it is clear and concise.
=> some functional changes

README.md
The readme file had an extra line from the old example code.  Feel free to discard this commit and amend your previous commit
=> README.md: remove invalid extra line in example code

src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONParsingUtils.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONSessionStatusParser.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONSessionStatusParser.java, src/test/resources/test_json.json
As stated this change adds all im channels to the already existing channel list. This results in more channels than before and could change (break) behavior. 
An alternative would be a separate im channel list...
=> Add im channels to the channel list

.gitignore, build.gradle, src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, src/main/java/com/ullink/slack/simpleslackapi/impl/AbstractSlackSessionImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackUserImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONSessionStatusParser.java
I need to register a connected listener so that I could stop my bot form answering itself :-)
Hop these changes work for you.
=> Added a Connected Listener

build.gradle, src/main/java/com/ullink/slack/simpleslackapi/SlackFile.java, src/main/java/com/ullink/slack/simpleslackapi/SlackMessage.java, src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, src/main/java/com/ullink/slack/simpleslackapi/events/SlackMessagePosted.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackMessagePostedImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackUserImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
With these changes users can now receive data about uploaded files.
I.e. you can now do something like:
if(event.getSlackFile() != null ){
String mediaUrl = event.getSlackFile().getUrl();
String comment = event.getSlackFile().getComment();
}
There is a new method on session for checking if socket connection is still open
=> File upload management into message management. Check session method

README.md
Disclaimer: I haven't compiled it
=> Code review of the full example :)

src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONReplyParser.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackReplyImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
two methods I needed for a project. Thought you might want to include them
=> added inviteToChannel and archiveChannel

src/main/java/com/ullink/slack/simpleslackapi/events/ReactionAdded.java, src/main/java/com/ullink/slack/simpleslackapi/events/ReactionRemoved.java, src/main/java/com/ullink/slack/simpleslackapi/impl/ReactionAddedImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/ReactionRemovedImpl.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
Correctly parse reactions to files.
Also fix a significant bug where new channels were always parsed as
isDirect=true.
=> Correctly parse reactions to files. + bug fix

gradle.properties, src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java, src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
This should fix the problem with #48.
Also added gradle daemon
=> removed param to send attachment over websocket

.gitignore, samples/actions/src/main/java/actions/RetrieveInformation.java, sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackEmojiReplyImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONReplyParser.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/replies/EmojiSlackReply.java, sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java, sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
Invoked using method
```
session.listEmoji();
```
Reference
https://api.slack.com/methods/emoji.list
=> Add list emoji

sources/src/main/java/com/ullink/slack/simpleslackapi/SlackPreparedMessage.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
https://api.slack.com/methods/chat.postMessage
=> support postMessage link_names

sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
Fixes https://github.com/Ullink/simple-slack-api/issues/86
=> Bot ID Patch

sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, sources/src/main/java/com/ullink/slack/simpleslackapi/events/EventType.java, sources/src/main/java/com/ullink/slack/simpleslackapi/events/PresenceChange.java, sources/src/main/java/com/ullink/slack/simpleslackapi/events/SlackEventType.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/AbstractSlackSessionImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/PresenceChangeImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/listeners/PresenceChangeListener.java
Hi! I've added presence_change event handling. Please take a look.
=> PresenceChange event

sources/src/main/java/com/ullink/slack/simpleslackapi/SlackAttachment.java, sources/src/main/java/com/ullink/slack/simpleslackapi/events/SlackMessagePosted.java, sources/src/main/java/com/ullink/slack/simpleslackapi/events/SlackMessageUpdated.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONAttachmentFormatter.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackMessagePostedImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackMessageUpdatedImpl.java, sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
=> Add support for attachments

sources/src/main/java/com/ullink/slack/simpleslackapi/SlackAction.java, sources/src/main/java/com/ullink/slack/simpleslackapi/SlackAttachment.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONAttachmentFormatter.java
Improve API for slack actions (buttons) by increasing functionality. Adds support for confirmation dialogue and styling.
=> Action API Enhancements

sources/src/main/java/com/ullink/slack/simpleslackapi/events/ReactionAdded.java, sources/src/main/java/com/ullink/slack/simpleslackapi/events/ReactionRemoved.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/ReactionAddedImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/ReactionRemovedImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
=> Add event timestamp to ReactionAdded and ReactionRemoved events.

sources/src/main/java/com/ullink/slack/simpleslackapi/impl/DefaultWebSocketContainerProvider.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackSessionFactory.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
Tested with https://hub.docker.com/r/babim/squid/
=> Uses proxy with password authentication.

README.md, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
The existing reconnect feature does not work
The proposed solution calls the `disconnectImpl()` and then `connectImpl()`
=> Fixed Reconnect

sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSessionWrapper.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/AbstractSlackSessionImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java, sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
Added the latest API method `chat.postEphemeral` keeping the code consistent with the `chat.postMessage` methods
=> Added chat.postEphemeral API

sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSessionWrapper.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java, sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
Add to sendFile method the following arguments:
* title
* initial_comment
=> Add more arguments to sendFile method

.travis.yml, README.md, gradle/scripts/coverage.gradle, sources/build.gradle
* use jacoco to generate coverage report
* use coveralls and add badge to `README.md`
tested from my [fork](https://github.com/leolin310148/simple-slack-api)
to make the badge working you will need to activate this project on http://coveralls.io/
=> add coverage badge

sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
https://api.slack.com/events/channel_rename
=> correctly parse rename channel obj

sources/src/main/java/com/ullink/slack/simpleslackapi/events/SlackEvent.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java
=> Replaced usages of SlackEvent.UNKNOWN_EVENT with UnkownEvent

sources/src/main/java/com/ullink/slack/simpleslackapi/SlackPreparedMessage.java
Need this in tests to mock message sending for specific message
=> Added equals and hashCode for SlackPreparedMessage

sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONMessageParser.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java
Because PR [#245] is not updated for over a year, I just did a diff between resources and updated the files accordingly.
=> Updated version of PR 245

samples/actions/src/main/java/actions/SendingMessages.java, samples/connection/src/main/java/com/ullink/slack/simpleslackapi/samples/connection/SlackCustomConnection.java, samples/connection/src/main/java/com/ullink/slack/simpleslackapi/samples/connection/SlackDirectConnection.java, samples/connection/src/main/java/com/ullink/slack/simpleslackapi/samples/connection/SlackDirectConnectionWithBuilder.java, samples/connection/src/main/java/com/ullink/slack/simpleslackapi/samples/connection/SlackProxyConnection.java, simpleslackapi.ipr, sources/src/main/java/com/ullink/slack/simpleslackapi/SlackPersona.java, sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java, sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSessionWrapper.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/ChannelHistoryModuleImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackIntegrationUser.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONParsingUtils.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONSessionStatusParser.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackPersonaImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackSessionFactory.java, sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java, sources/src/main/java/com/ullink/slack/simpleslackapi/replies/SlackChannelReply.java, sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestAbstractSlackSessionImpl.java, sources/src/test/java/com/ullink/slack/simpleslackapi/impl/TestSlackJSONMessageParser.java
Issues fixed:
#289 
#279 
#284
=> Fix Auth plus various issues
